KNOWN_PRODUCTS = [
    "Atirpinta spurga ASORTI su įdaru, 65 g",
    "Atšaldyta kiaulienos nugarinė be kaulo, 1 kg",
    "Avietinės vaisių juostelės VERI BERI, 50g",
    "Avokadas, 1 vnt",
    "Balzamas SYOSS Repair 440ml",
    "Bananai Cavendish, 20+cm 1kg",
    "Bananų ir braškių gėrimas CIDO KIDS, 0,2 l",
    "Bandelė su plikytu kremu ir šokoladu, 66 g",
    "Batonėliai su sūr. karam. SALLING, 6x25 g",
    "Batonėlis su saldik. GO ON CRISP COOKIE, 50 g",
    "Braškių skonio gl. desertas MILIKO, 35 g",
    "Brokolis RIMI, 350 g",
    "Dantų krapštukai, sterilizuotos 300vnt",
    "Dribsnių batonėlis braškių skonio RIMI, 30 g",
    "Fas. obuoliai GALA MUST, 1 kl., 1kg",
    "FOCACCIA bandelė su grybais ir sūriu, 70 g",
    "Gaivusis gėrimas 7UP, 1,5l",
    "Gaivusis gėrimas 7UP, 500ml",
    "Gaz.natūral. mineralinis vanduo BIRUTĖ, 1,5l",
    "Gazuotas gėrimas su saldikliais PEPSI MAX, 1l",
    "Gazuotas gaivusis gėrimas SPRITE ZERO, 1,5 l",
    "Gl.varšk.sūrelis van.sk.VILK.LESS SUGAR, 40 g",
    "Gouda sūrio užkandis FINGIES, 250 g",
    "Gr. par. makaronai NONGSHIM CHAPAGETTI, 140 g",
    "Griet. svog. sk. bulv. trašk. ESTRELLA, 130g",
    "Guav. drak. v. sulčių gėr. GRANINI S. 0,75 l",
    "Izot. gėrimas 4MOVE ZERO MULTIFRUIT, 750 ml",
    "Jogurtas su brašk. GRAIKIŠKA AMFORA, 3,1%, 150g",
    "Jogurtas su med. GRAIKIŠKA AMFORA, 3,1%, 150g",
    "Kavos gėr. JACOBS 3in1 CINAMON ROLL, 11,2 g",
    "Kiaulienos mentė be kaulo, VAK. 1 kg",
    "Kruasanas su sviestu, 58 g",
    "Kvietinės tortilijos RIMI PLANET, 370 g",
    "Maži ryžių trapučiai su paprika RIMI, 60 g",
    "Obuoliai RED JONAPRINCE, 1 kl., 1kg",
    "Pienas be laktozės MARGĖ, 1,5%, UAT, 1 l",
    "Pjaustyti morkų šiaudeliai FIT & EASY, 200 g",
    "Pyragėlis su kremu Pastel de Nata, 50 g",
    "Rankų darbo itališka duona CIABATTA, 350 g",
    "Raud. saldžiosios paprikos (70+),1kl,1kg",
    "Raud. saldžiosios paprikos (80+),1kl,1kg",
    "Riešutų batonėlis RIMI su migdolais, 35 g",
    "Saus. su lazdynų riešutų kr. SALLING, 175 g",
    "Sumuštinis su rūkytu kumpiu BOMBER, 230 g",
    "Šald. pranc. batonai česn. įd. MANTINGA, 350g",
    "Šaldyti blyneliai su šokolado įdaru VICI, 340g",
    "Šampūnas SYOSS Repair 440ml",
    "Švieži kopūstai, 1 kg",
    "Tarkuotas sūris MOZZARELLA GALBANI, 20%, 150 g",
    "Traškučiai OHO! Mexicana, 60g",
    "Traškučiai su grietine ir svogūnais OHO!, 60g",
    "Vaisių ir rieš užkandis GREENZ APRICOT, 30 g",
    "Vanil. ledai su karam. saus. DIONE ZERO, 500ml",
    "Vanilinis pieno gėrimas MIAU, 450 ml",
    "Varškės sūrelis su kond. pienu NYKŠTUKAS, 45 g",
    "Varškės spurga, 72 g",
    "Viščiukų filė be antibiotikų RIMI, 500 g",
    "Virta dešra griež., KAI NORISI MĖSOS, 190g",
    "Žal. citr., paprikų sk. trapučiai RIMI, 60 g",
    "Gazuotas gaivusis gėrimas SPRITE ZERO, 1,5 l",
    "Energ. gėr. RED BULL WINTER EDITION, 0,25 l",
    "Nealkoholinis sidras SOMERSBY PEAR, 0,5 l",
    "Gaz. kolos sk. gaiv. gėrimas COCA COLA ZERO, 1 l",
    "Gazuotas gaiv. gėrimas COCA-COLA CHERRY, 1 l",
    "Gr. paruoš. mak. ter. sk. MAGGI MAGIC ASIA, 130 g",
    "Makaronai MAGGI 5 MINUTES CARBONARA, 50 g",
    "Bulvių košė su svog. skreb. MAGGI 5 MIN, 59 g",
    "Makaron. griet. pom. pad. MAGGI 5 MINUTES, 62 g",
    "Korėj. stil. koldūnai su BBQ mėsa VICI, 300 g",
    "Pievagrybiai RIMI, 250 g",
    "Rudieji pievagrybiai RIMI, 250 g",
    "Atšaldyta smulkinta kiauliena, 30%, 1kg",
    "Viščiukų vidinė filė be antib. RIMI, 400 g",
    "Sviestas RIMI SMART, 82% rieb., 180 g",
    "Sūris RIMI SMART TILSIT 45%, 250 g",
    "Traškučiai OHO! Mexicana, 60 g",
    "Sausainiai GAIDELIS SPANGUOLĖ, 160 g",
    "Vaflinis batonėlis KINDER BUENO, 43 g",
    "Kavos gėrimas HOCHWALD EISKAFFEE, 500 ml",
    "Gazuotas vanduo AKVILĖ, 1,5 l",
    "Pienas ROKIŠKIO BE LAKTOZĖS, 2,5%, 1 l",
    "Mocarela sūris RIMI tarkuotas, 150 g",
    "Graikiškas jogurtas AMFORA, 3,9%, 200 g",
    "Sluoksniuota bemielė tešla MANTINGA, 500 g",
    "Koldūnai LIŪTUKAS, 700 g",
    "Brokolis RIMI, 350 g",
    "Morkų šiaudeliai FIT & EASY, 200 g",
    "Obuoliai RED JONAPRINCE, 1 kl., 1kg",
    "Bananai Cavendish, 1kg",
]